[package]
name = "musig2"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.9"
secp256k1 = { path = "../crypto-rs", package = "crypto-rs"  }
num-bigint = "0.4.6"
num-traits = "0.2.19"
rand = "0.9.1"
